version: "3.7"

x-logging: &default-logging
  driver: syslog
  options:
    syslog-address: "tcp://127.0.0.1:514"

services:
  endpoint:
    image: "itworks99/narwhal_endpoint"
    ports:
      - 514:514
    environment:
      REMOTE_REDIS_HOST: "data"
    depends_on:
      - data
    links:
      - data
    logging: *default-logging

  server:
    image: "itworks99/narwhal"
    ports:
      - "3000:3000"
      - "8080:3000"
      - "80:3000"
      - "8000:3000"
    environment:
      REMOTE_REDIS_HOST: "data"
      DASHBOARD_WEB_INTERFACE: "0.0.0.0"
      DASHBOARD_WEB_PORT: "3000"
    depends_on:
      - data
    links:
      - data
    logging: *default-logging

  data:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    # logging: *default-logging
